const APA_DATA={
  insignias:[
    {id:1,nombre:"Primera Lección",descripcion:"Completa tu primera lección",icono:"🎯",condicion_tipo:"lecciones",condicion_valor:1},
    {id:2,nombre:"Racha 3 días",descripcion:"Practica 3 días seguidos",icono:"🔥",condicion_tipo:"racha",condicion_valor:3},
    {id:3,nombre:"Racha 7 días",descripcion:"Practica 7 días seguidos",icono:"⚡",condicion_tipo:"racha",condicion_valor:7},
    {id:4,nombre:"Nivel Básico",descripcion:"Completa las 5 lecciones básicas",icono:"🌱",condicion_tipo:"lecciones",condicion_valor:5},
    {id:5,nombre:"Nivel Intermedio",descripcion:"Completa 10 lecciones",icono:"📘",condicion_tipo:"lecciones",condicion_valor:10},
    {id:6,nombre:"Maestro APA",descripcion:"Completa las 15 lecciones",icono:"🏆",condicion_tipo:"lecciones",condicion_valor:15},
    {id:7,nombre:"100 XP",descripcion:"Acumula 100 puntos de experiencia",icono:"⭐",condicion_tipo:"xp",condicion_valor:100},
    {id:8,nombre:"300 XP",descripcion:"Acumula 300 puntos de experiencia",icono:"💫",condicion_tipo:"xp",condicion_valor:300},
    {id:9,nombre:"Perfeccionista",descripcion:"Completa 5 lecciones sin errores",icono:"💎",condicion_tipo:"perfectas",condicion_valor:5},
    {id:10,nombre:"Experto Citador",descripcion:"Responde 30 preguntas correctamente",icono:"✅",condicion_tipo:"precision",condicion_valor:30}
  ],
  niveles:[
    {id:1,nombre:"Básico",subtitulo:"Fundamentos de APA 7",emoji:"🌱",color:"#20C997",xpRequerido:0,
     lecciones:[
      {id:"L1-1",titulo:"¿Qué son las Normas APA?",emoji:"📖",xp:20,
       teoria:"<h3>Normas APA — 7ma Edición</h3><p><strong>APA</strong> = American Psychological Association. La <strong>7ma edición (2019)</strong> es la vigente.</p><div class=\"tex ok\"><span class=\"tlb\">¿Para qué sirven?</span><ul><li>Estandarizar el formato académico</li><li>Dar crédito a las fuentes</li><li>Prevenir el plagio</li></ul></div>",
       preguntas:[
        {id:"q1",texto:"¿Qué significa la sigla APA?",opciones:["American Psychological Association","American Publishing Association","Academic Psychology Association","Applied Papers Association"],correcta:0,explicacion:"APA = American Psychological Association, fundada en 1892."},
        {id:"q2",texto:"¿En qué año se publicó la 7ma edición de APA?",opciones:["2015","2017","2019","2021"],correcta:2,explicacion:"La 7ma edición fue publicada en 2019 y es la versión más reciente."},
        {id:"q3",texto:"¿Cuál es el objetivo principal de las Normas APA?",opciones:["Decorar los trabajos","Estandarizar el formato y la citación académica","Limitar el número de referencias","Solo aplica para psicología"],correcta:1,explicacion:"Las normas APA estandarizan la escritura para facilitar la comunicación académica."},
        {id:"q4",texto:"¿Las Normas APA solo se usan en psicología?",opciones:["Sí, son exclusivas","No, se usan en ciencias sociales, educación y más","Sí, también en medicina","No, solo en ingeniería"],correcta:1,explicacion:"Las Normas APA se aplican en educación, comunicación, enfermería y muchas otras áreas."},
        {id:"q5",texto:"¿Qué problema principal resuelven las Normas APA?",opciones:["La extensión de documentos","Los problemas de gramática","El plagio y la falta de estandarización","La falta de ilustraciones"],correcta:2,explicacion:"Las normas APA establecen cómo citar para dar crédito y evitar el plagio."}
       ]},
      {id:"L1-2",titulo:"Formato del Documento",emoji:"📄",xp:20,
       teoria:"<h3>Formato General APA 7</h3><table class=\"tth\"><tr><th>Elemento</th><th>Valor</th></tr><tr><td>Márgenes</td><td>2.54 cm en todos los lados</td></tr><tr><td>Fuente</td><td>Arial 11pt / Times New Roman 12pt</td></tr><tr><td>Interlineado</td><td>Doble en todo el documento</td></tr><tr><td>Alineación</td><td>Izquierda (no justificado)</td></tr><tr><td>Páginas</td><td>Esquina superior derecha</td></tr></table>",
       preguntas:[
        {id:"q6",texto:"¿Cuánto deben medir los márgenes en APA 7?",opciones:["1.5 cm","2 cm","2.54 cm (1 pulgada)","3 cm"],correcta:2,explicacion:"APA 7 establece márgenes de 2.54 cm en todos los lados."},
        {id:"q7",texto:"¿Cuál es el interlineado correcto en APA 7?",opciones:["Simple","1.5","Doble","Triple"],correcta:2,explicacion:"El interlineado doble se aplica en todo el documento."},
        {id:"q8",texto:"¿Cuál fuente es aceptada en APA 7?",opciones:["Comic Sans 12pt","Arial 11pt","Verdana 14pt","Impact 10pt"],correcta:1,explicacion:"APA 7 acepta: Arial 11pt, Times New Roman 12pt, Calibri 11pt."},
        {id:"q9",texto:"¿Cómo debe alinearse el texto en APA 7?",opciones:["Centrado","Justificado","Alineado a la izquierda","Alineado a la derecha"],correcta:2,explicacion:"APA 7 recomienda alineación a la izquierda (ragged right)."},
        {id:"q10",texto:"¿Dónde va el número de página en APA 7?",opciones:["Solo primera página","Esquina inferior derecha","Esquina superior derecha","No se numeran"],correcta:2,explicacion:"Los números de página van en el encabezado, esquina superior derecha."}
       ]},
      {id:"L1-3",titulo:"Citas Directas Cortas",emoji:"✏️",xp:25,
       teoria:"<h3>Citas Directas Cortas (&lt;40 palabras)</h3><p>Reproduce <strong>exactamente</strong> las palabras del autor. Menos de 40 palabras: va entre comillas en el párrafo.</p><div class=\"tex ok\"><span class=\"tlb\">Formato correcto</span><p>García (2020) señaló que <em>la educación es el arma más poderosa</em> (p. 45).</p></div><p>Siempre incluye: <strong>Apellido, año y número de página</strong></p>",
       preguntas:[
        {id:"q11",texto:"¿Cuántas palabras máximo puede tener una cita directa corta?",opciones:["20","30","Menos de 40","50"],correcta:2,explicacion:"Una cita es corta si tiene menos de 40 palabras."},
        {id:"q12",texto:"¿Cómo se presenta una cita directa corta?",opciones:["En cursiva sin comillas","Entre comillas integrada en el párrafo","En línea aparte con sangría","En negrita entre paréntesis"],correcta:1,explicacion:"Las citas directas cortas van entre comillas dobles integradas en el párrafo."},
        {id:"q13",texto:"¿Qué tres elementos debe incluir una cita directa?",opciones:["Título, año, URL","Apellido, año y número de página","Solo apellido y año","Nombre completo, fecha y párrafo"],correcta:1,explicacion:"Toda cita directa requiere: apellido, año y número de página."},
        {id:"q14",texto:"¿Cuál cita directa está CORRECTAMENTE formateada?",opciones:["Garcia (2020) menciona [la educación] p.45","García (2020) señaló que la educación es fundamental (p. 45).","García, 2020, la educación, p. 45","(García: la educación, 2020, p. 45)"],correcta:1,explicacion:"Formato: Apellido (Año) entre comillas (p. XX)."},
        {id:"q15",texto:"Si el autor se menciona al inicio, ¿cómo va la cita?",opciones:["(García, 2020) la educación","García (2020) afirmó que la educación transforma (p. 45).","García: la educación (2020, pág. 45)","García dijo la educación p. 45"],correcta:1,explicacion:"Cuando el autor es sujeto, el año va junto al nombre y la página al final."}
       ]},
      {id:"L1-4",titulo:"Paráfrasis",emoji:"💬",xp:25,
       teoria:"<h3>Citas con Paráfrasis</h3><p>Expresar las ideas de otro autor con <strong>tus propias palabras</strong>.</p><div class=\"tex ok\"><span class=\"tlb\">Correcto</span><p>Según García (2020), la educación tiene el potencial de transformar la sociedad.</p></div><div class=\"tex bad\"><span class=\"tlb\">Incorrecto — plagio</span><p>García dice que la educación es el arma más poderosa. — sin citar</p></div>",
       preguntas:[
        {id:"q16",texto:"¿Qué es la paráfrasis en APA?",opciones:["Copiar con comillas","Expresar ideas ajenas con tus propias palabras","Resumir sin citar al autor","Traducir textos literalmente"],correcta:1,explicacion:"Parafrasear es reescribir la idea del autor con palabras propias, siempre citando."},
        {id:"q17",texto:"¿Es obligatorio el número de página en una paráfrasis?",opciones:["Sí, siempre","No, solo apellido y año (página recomendada)","No necesita referencia","Sí, y el título además"],correcta:1,explicacion:"APA 7 requiere apellido y año. La página es recomendada pero no obligatoria."},
        {id:"q18",texto:"¿Cuál es un ejemplo CORRECTO de paráfrasis?",opciones:["La educación transforma vidas (García, 2020) entre comillas","Según García (2020), la educación tiene poder transformador.","García dice que la educación transforma sin citar","García dice la educación [García, 2020]"],correcta:1,explicacion:"La paráfrasis usa palabras propias y cita con apellido y año. Sin comillas."},
        {id:"q19",texto:"¿Por qué es importante la paráfrasis?",opciones:["Para evitar referencias","Para demostrar comprensión y evitar el plagio","Para hacer el texto más corto","Porque es obligatoria por ley"],correcta:1,explicacion:"La paráfrasis demuestra comprensión del material."},
        {id:"q20",texto:"¿Cuál es un ejemplo de PLAGIO al parafrasear?",opciones:["García (2020) plantea que la enseñanza revoluciona la sociedad.","La educación revoluciona la sociedad (García, 2020).","La educación es el arma más poderosa para cambiar el mundo. García 2020.","Según García (2020), aprender cambia el rumbo de las naciones."],correcta:2,explicacion:"Copiar el texto original sin comillas ni cita correcta es plagio."}
       ]},
      {id:"L1-5",titulo:"Referencias: Libros",emoji:"📚",xp:30,
       teoria:"<h3>Referencias de Libros — APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">Formato básico</span><p>Apellido, I. (Año). <em>Título del libro</em>. Editorial.</p></div><div class=\"tex ok\"><span class=\"tlb\">Ejemplo</span><p>García, J. A. (2020). <em>Fundamentos de educación</em>. Universidad Nacional.</p></div><div class=\"tex bad\"><span class=\"tlb\">ERROR APA 7: ya no va el lugar</span><p>García, J. A. (2020). Título. ~~México:~~ UNAM.</p></div>",
       preguntas:[
        {id:"q21",texto:"¿Cómo se escribe el título del libro en referencias APA 7?",opciones:["EN MAYÚSCULAS","Entre comillas","En cursiva","En negrita"],correcta:2,explicacion:"El título del libro va en cursiva en la lista de referencias."},
        {id:"q22",texto:"¿Se incluye la ciudad de publicación en APA 7?",opciones:["Sí, siempre","No, APA 7 eliminó el lugar de publicación","Solo si es extranjero","Solo si la editorial es desconocida"],correcta:1,explicacion:"APA 7 eliminó el lugar de publicación."},
        {id:"q23",texto:"¿Cuál referencia de libro está CORRECTAMENTE formateada?",opciones:["Garcia J.A. (2020). Fundamentos. México: UNAM.","García, J. A. (2020). Fundamentos de educación. Universidad Nacional.","García, Juan Antonio. (2020). Fundamentos entre comillas. UNAM.","J. A. García. 2020. Fundamentos. Universidad."],correcta:1,explicacion:"Formato: Apellido, I. (Año). Título en cursiva. Editorial."},
        {id:"q24",texto:"¿Cómo se cita un libro en el texto (parentética)?",opciones:["(García, J.A., 2020)","(García 2020)","(García, 2020)","(García:2020)"],correcta:2,explicacion:"Cita parentética básica: (Apellido, año)."},
        {id:"q25",texto:"¿Qué inicial se usa para el nombre del autor en APA 7?",opciones:["El nombre completo","Solo la primera inicial","Primeras dos iniciales","Sin iniciales"],correcta:1,explicacion:"Se usa solo la primera inicial del nombre. Ej: García, J. A."}
       ]}
     ]},
    {id:2,nombre:"Intermedio",subtitulo:"Citas y Referencias Avanzadas",emoji:"📘",color:"#4C6EF5",xpRequerido:80,
     lecciones:[
      {id:"L2-1",titulo:"Múltiples Autores",emoji:"👥",xp:30,
       teoria:"<h3>Citar Múltiples Autores</h3><table class=\"tth\"><tr><th>Autores</th><th>Narrativa</th><th>Parentética</th></tr><tr><td>1</td><td>García (2020)</td><td>(García, 2020)</td></tr><tr><td>2</td><td>García y López (2020)</td><td>(García &amp; López, 2020)</td></tr><tr><td>3+</td><td>García et al. (2020)</td><td>(García et al., 2020)</td></tr></table><p><strong>&amp;</strong> dentro del paréntesis · <strong>y</strong> fuera</p>",
       preguntas:[
        {id:"q26",texto:"¿Cómo se cita un trabajo de 3+ autores en APA 7?",opciones:["García, López y Martínez (2020)","García et al. (2020)","García y otros (2020)","Todos los autores siempre"],correcta:1,explicacion:"Con 3+ autores siempre: Primer apellido et al. (año)."},
        {id:"q27",texto:"¿Qué conector va entre 2 autores DENTRO de un paréntesis?",opciones:["y","&",",","-"],correcta:1,explicacion:"Dentro del paréntesis se usa &. Fuera se usa y."},
        {id:"q28",texto:"¿Cómo se citan 2 autores en narrativa (fuera del paréntesis)?",opciones:["García & López (2020)","García y López (2020)","García, López (2020)","García/López (2020)"],correcta:1,explicacion:"Fuera del paréntesis: García y López (2020)."},
        {id:"q29",texto:"En referencias con 21+ autores ¿qué se hace?",opciones:["Solo el primero","Los primeros 19, ..., el último","Solo los primeros 3","Se escribe et al."],correcta:1,explicacion:"Con 21+ autores en referencias: primeros 19, puntos suspensivos, último."},
        {id:"q30",texto:"¿Cuál cita parentética de 2 autores es CORRECTA?",opciones:["(García and López, 2020)","(García & López, 2020)","(García; López, 2020)","(García, López 2020)"],correcta:1,explicacion:"Dos autores en paréntesis: (Apellido & Apellido, año)."}
       ]},
      {id:"L2-2",titulo:"Citas Directas Largas",emoji:"📋",xp:30,
       teoria:"<h3>Citas en Bloque (40+ palabras)</h3><div class=\"tex ok\"><span class=\"tlb\">Características del bloque</span><ul><li>Nueva línea, sangría <strong>1.27 cm</strong></li><li><strong>Sin comillas</strong></li><li>Interlineado doble</li><li>Punto va <strong>ANTES</strong> del paréntesis</li></ul></div><div class=\"tex ok\"><span class=\"tlb\">Ejemplo del punto</span><p>...texto del autor. (García, 2020, p. 45)</p></div>",
       preguntas:[
        {id:"q31",texto:"¿Cuántas palabras mínimo para cita en bloque?",opciones:["30","35","40","50"],correcta:2,explicacion:"Una cita se convierte en bloque con 40 palabras o más."},
        {id:"q32",texto:"¿Cómo se presenta una cita en bloque?",opciones:["Entre comillas como texto normal","Bloque separado con sangría, sin comillas","En cursiva con sangría derecha","Como nota al pie"],correcta:1,explicacion:"Bloque: texto separado, sangría 1.27 cm, sin comillas."},
        {id:"q33",texto:"En cita en bloque, ¿dónde va el punto?",opciones:["texto (García, 2020, p. 45).","texto. (García, 2020, p. 45)","(García, 2020, p. 45) texto.","texto, (García 2020, p. 45)."],correcta:1,explicacion:"En bloque: el punto va ANTES de la referencia parentética."},
        {id:"q34",texto:"¿Se usan comillas en una cita en bloque?",opciones:["Sí, siempre","No, las comillas se omiten","Solo al inicio","Solo si hay comillas en el original"],correcta:1,explicacion:"Las citas en bloque no llevan comillas externas."},
        {id:"q35",texto:"¿Cuál es la sangría para una cita en bloque?",opciones:["0.5 cm","1.27 cm (media pulgada)","2.54 cm","5 cm"],correcta:1,explicacion:"La sangría es de 1.27 cm desde el margen izquierdo."}
       ]},
      {id:"L2-3",titulo:"Referencias: Artículos",emoji:"📰",xp:35,
       teoria:"<h3>Artículos de Revista — APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">Formato</span><p>Apellido, I. (Año). Título artículo. <em>Nombre Revista, Vol</em>(Núm), pp–pp. https://doi.org/xxx</p></div><p>En <strong>cursiva</strong>: nombre de la revista y volumen. El número entre paréntesis NO va en cursiva.</p>",
       preguntas:[
        {id:"q36",texto:"¿Qué elementos van en cursiva en un artículo APA 7?",opciones:["El título del artículo","El nombre de la revista y el volumen","El DOI y las páginas","El nombre del autor"],correcta:1,explicacion:"En artículos: nombre de revista y número de volumen van en cursiva."},
        {id:"q37",texto:"¿Cuál es el orden correcto en referencia de artículo?",opciones:["Título, Autor, Año, Revista","Autor, Año, Título, Revista, Vol(Núm), Páginas, DOI","Revista, Año, Autor, Título","Año, Autor, Revista, Título"],correcta:1,explicacion:"Orden APA 7: Autor. (Año). Título. Revista, Vol(Núm), páginas. DOI"},
        {id:"q38",texto:"¿Qué significa DOI?",opciones:["Digital Online Identifier","Digital Object Identifier","Document Organization Index","Database Open Interface"],correcta:1,explicacion:"DOI = Digital Object Identifier, identificador único permanente."},
        {id:"q39",texto:"¿Cuál es el formato correcto para el DOI en APA 7?",opciones:["doi:10.1234/ejemplo","DOI: 10.1234/ejemplo","https://doi.org/10.1234/ejemplo","www.doi.org/10.1234/ejemplo"],correcta:2,explicacion:"En APA 7, el DOI se escribe como URL activa: https://doi.org/10.xxxx"},
        {id:"q40",texto:"¿El número de la revista va en cursiva?",opciones:["Sí, siempre","No, solo el volumen va en cursiva","Sí, entre paréntesis","No, nada va en cursiva"],correcta:1,explicacion:"El volumen va en cursiva; el número entre paréntesis NO."}
       ]},
      {id:"L2-4",titulo:"Referencias: Páginas Web",emoji:"🌐",xp:35,
       teoria:"<h3>Páginas Web — APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">Con autor</span><p>Apellido, I. (Año, día mes). <em>Título</em>. Sitio. URL</p></div><div class=\"tex ok\"><span class=\"tlb\">Sin autor</span><p><em>Título</em>. (Año). Sitio. URL</p></div><div class=\"tex bad\"><span class=\"tlb\">Error APA 7</span><p>NO escribir Recuperado de antes de la URL</p></div>",
       preguntas:[
        {id:"q41",texto:"¿Qué se escribe cuando no hay fecha de publicación?",opciones:["Se omite la fecha","Se escribe (s.f.)","Se escribe sin fecha","Se pone la fecha de acceso"],correcta:1,explicacion:"Sin fecha se escribe (s.f.) — sin fecha."},
        {id:"q42",texto:"¿Se debe escribir Recuperado de antes de la URL en APA 7?",opciones:["Sí, siempre","Solo en páginas web","No, APA 7 eliminó esa frase","Solo sin fecha"],correcta:2,explicacion:"APA 7 eliminó la frase Recuperado de."},
        {id:"q43",texto:"¿Qué va en cursiva en referencia de página web?",opciones:["La URL","El nombre del sitio","El título de la página específica","La fecha"],correcta:2,explicacion:"El título de la página específica va en cursiva."},
        {id:"q44",texto:"Si la página web no tiene autor, ¿cómo empieza la referencia?",opciones:["Se escribe Anónimo","Se escribe Sin autor","El título de la página va primero","Se omite la referencia"],correcta:2,explicacion:"Sin autor, el título ocupa el lugar del autor al inicio."},
        {id:"q45",texto:"¿Cuándo se incluye fecha de acceso en referencias web?",opciones:["Siempre","Nunca","Solo cuando el contenido puede cambiar","Solo para redes sociales"],correcta:2,explicacion:"La fecha de acceso solo se incluye cuando el contenido podría cambiar constantemente."}
       ]},
      {id:"L2-5",titulo:"Páginas y Párrafos",emoji:"🔢",xp:30,
       teoria:"<h3>Indicar Ubicación en las Citas</h3><table class=\"tth\"><tr><th>Situación</th><th>Formato</th><th>Ejemplo</th></tr><tr><td>Una página</td><td>p. XX</td><td>(García, 2020, p. 45)</td></tr><tr><td>Varias páginas</td><td>pp. XX-XX</td><td>(García, 2020, pp. 45-47)</td></tr><tr><td>Sin páginas</td><td>párr. X</td><td>(García, 2020, párr. 3)</td></tr></table>",
       preguntas:[
        {id:"q46",texto:"¿Cómo se indica un número de página en APA 7?",opciones:["pág. 45","pg. 45","p. 45","P. 45"],correcta:2,explicacion:"La abreviatura correcta para página es p. (minúscula, con punto)."},
        {id:"q47",texto:"¿Cómo se indica un rango de páginas en APA 7?",opciones:["p. 45-47","pp. 45-47","p. 45 a 47","pgs. 45-47"],correcta:1,explicacion:"Para rango de páginas se usa pp. (plural)."},
        {id:"q48",texto:"Si la fuente digital no tiene paginación, ¿qué usas?",opciones:["No es necesario","párr. 3 (número de párrafo)","sec. 3","línea 3"],correcta:1,explicacion:"Sin páginas, usa párr. seguido del número de párrafo."},
        {id:"q49",texto:"¿Cuál indicación de ubicación está bien en APA 7?",opciones:["(García, 2020, pagina 15)","(García, 2020, p. 15)","(García, 2020, Pág. 15)","(García, 2020: 15)"],correcta:1,explicacion:"Formato correcto: (Apellido, año, p. número)."},
        {id:"q50",texto:"¿Cómo se cita un párrafo sin páginas?",opciones:["(García, 2020, pg. 2)","(García, 2020, párr. 2)","(García, 2020, p. 2)","(García, 2020, sec. 2)"],correcta:1,explicacion:"Sin paginación: (Apellido, año, párr. número)."}
       ]}
     ]},
    {id:3,nombre:"Avanzado",subtitulo:"Casos Especiales y Dominio Total",emoji:"🏆",color:"#E64980",xpRequerido:220,
     lecciones:[
      {id:"L3-1",titulo:"Sin Autor / Sin Fecha",emoji:"❓",xp:40,
       teoria:"<h3>Obras sin Autor o sin Fecha</h3><div class=\"tex ok\"><span class=\"tlb\">Sin autor — en el texto</span><p>(Primeras palabras del título entre comillas, Año)</p></div><div class=\"tex ok\"><span class=\"tlb\">Sin fecha</span><p>Apellido, I. (s.f.). <em>Título</em>. Editorial. En texto: (Apellido, s.f.)</p></div>",
       preguntas:[
        {id:"q51",texto:"¿Cómo se cita en el texto una obra sin autor?",opciones:["Se escribe Anónimo","Las primeras palabras del título entre comillas","Se omite la cita","Se escribe autor desconocido"],correcta:1,explicacion:"Sin autor, se usan las primeras palabras del título entre comillas."},
        {id:"q52",texto:"¿Qué abreviatura se usa cuando no hay fecha?",opciones:["n/a","n.d.","s.f.","s/n"],correcta:2,explicacion:"En español: s.f. (sin fecha). En inglés: n.d."},
        {id:"q53",texto:"¿Cuál es la cita correcta para artículo sin autor titulado Técnicas APA?",opciones:["(Sin autor, 2020)","(Técnicas APA, 2020)","(Anónimo, 2020)","(2020, Técnicas APA)"],correcta:1,explicacion:"Sin autor: primeras palabras del título entre comillas + año."},
        {id:"q54",texto:"¿Qué va primero en referencias para obra sin autor?",opciones:["La fecha","El editor","El título","La editorial"],correcta:2,explicacion:"Sin autor, el título ocupa la posición del autor al inicio."},
        {id:"q55",texto:"¿Cómo se escribe la cita para obra sin autor ni fecha?",opciones:["(s.f., s.a.)","(Primeras palabras, s.f.)","(Anónimo, s.f.)","(título, sin fecha)"],correcta:1,explicacion:"Sin autor ni fecha: (Primeras palabras del título, s.f.)."}
       ]},
      {id:"L3-2",titulo:"Fuentes Secundarias",emoji:"🔄",xp:40,
       teoria:"<h3>Fuentes Secundarias (citado en...)</h3><p>Se usa cuando citas a un autor mencionado en otro texto que leíste.</p><div class=\"tex ok\"><span class=\"tlb\">En el texto</span><p>García (2018, como se citó en López, 2021) demostró que...</p></div><div class=\"tex ok\"><span class=\"tlb\">En referencias</span><p>Solo incluyes la fuente que leíste (López, 2021), NO la original.</p></div>",
       preguntas:[
        {id:"q56",texto:"¿Qué es una fuente secundaria en APA?",opciones:["Un libro de segunda mano","Un autor citado dentro de otro texto que leíste","Una fuente web no confiable","Una fuente de más de 10 años"],correcta:1,explicacion:"Fuente secundaria: un autor citado en otro texto que tú sí leíste."},
        {id:"q57",texto:"En referencias de fuente secundaria, ¿qué incluyes?",opciones:["Ambas fuentes","Solo la fuente original","Solo la fuente que realmente leíste","Ninguna"],correcta:2,explicacion:"Solo se incluye en referencias la fuente que realmente leíste."},
        {id:"q58",texto:"¿Cuál es el formato correcto para fuente secundaria?",opciones:["García (2018) como se citó en López (2021)","García y López (2021)","García (2018) y López (2021)","(García, 2018; López, 2021)"],correcta:0,explicacion:"Formato: Apellido_original (año, como se citó en Apellido_leído, año)."},
        {id:"q59",texto:"¿Qué año va en el paréntesis al final de fuente secundaria?",opciones:["(García, 2018)","(López, 2021)","(García & López, 2021)","(2018/2021)"],correcta:1,explicacion:"El paréntesis lleva el año del texto que realmente leíste."},
        {id:"q60",texto:"¿Cuándo recomienda APA 7 usar fuentes secundarias?",opciones:["Siempre que sea posible","Solo cuando no puedas obtener la fuente original","Nunca","Solo en posgrado"],correcta:1,explicacion:"APA recomienda buscar siempre la fuente original."}
       ]},
      {id:"L3-3",titulo:"DOI y URLs Avanzado",emoji:"🔗",xp:35,
       teoria:"<h3>DOI y URLs en APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">DOI correcto</span><p>https://doi.org/10.1234/ejemplo</p></div><div class=\"tex ok\"><span class=\"tlb\">Reglas clave</span><ul><li>Si tiene DOI, no incluyas la URL</li><li>Sin DOI: usa la URL de la página</li><li>NO escribir Recuperado de</li><li>NO poner punto al final del DOI/URL</li></ul></div>",
       preguntas:[
        {id:"q61",texto:"¿Cuál es el formato correcto de un DOI en APA 7?",opciones:["doi:10.1234/ej","DOI: 10.1234/ej","https://doi.org/10.1234/ej","www.doi.org/10.1234/ej"],correcta:2,explicacion:"El DOI se presenta como URL activa: https://doi.org/10.XXXX"},
        {id:"q62",texto:"Si un artículo tiene DOI, ¿también se incluye la URL?",opciones:["Sí, siempre ambos","No, el DOI es suficiente","Solo si la URL es más corta","Depende del tipo"],correcta:1,explicacion:"Con DOI disponible, no se incluye la URL."},
        {id:"q63",texto:"Si un artículo no tiene DOI, ¿qué se hace?",opciones:["La referencia no puede incluirse","Se escribe sin DOI","Se incluye la URL donde se encontró","Se deja vacío"],correcta:2,explicacion:"Sin DOI, se incluye la URL del artículo."},
        {id:"q64",texto:"¿Se debe escribir Recuperado de antes de URL en APA 7?",opciones:["Sí, siempre","Solo en páginas web","No, APA 7 eliminó esa frase","Solo sin fecha"],correcta:2,explicacion:"APA 7 eliminó completamente Recuperado de."},
        {id:"q65",texto:"¿Se pone punto al final de un DOI o URL en APA 7?",opciones:["Sí, como cualquier oración","No, para no corromper el enlace","Solo en el DOI","Solo si es el último elemento"],correcta:1,explicacion:"No se pone punto al final de DOIs o URLs."}
       ]},
      {id:"L3-4",titulo:"Tablas y Figuras",emoji:"📊",xp:40,
       teoria:"<h3>Tablas y Figuras en APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">TABLAS: número y título ARRIBA</span><p><strong>Tabla 1</strong><br><em>Título descriptivo</em><br>[contenido]<br><em>Nota.</em> Explicación.</p></div><div class=\"tex ok\"><span class=\"tlb\">FIGURAS: número y título ABAJO</span><p>[imagen]<br><strong>Figura 1</strong><br><em>Título descriptivo</em><br><em>Nota.</em> Fuente.</p></div>",
       preguntas:[
        {id:"q66",texto:"¿Dónde van número y título de una TABLA en APA 7?",opciones:["Debajo","Encima","Dentro","Al final"],correcta:1,explicacion:"En tablas: número (negrita) y título (cursiva) van ENCIMA."},
        {id:"q67",texto:"¿Cómo se formatea el número de tabla?",opciones:["En cursiva","En negrita","Subrayado","Normal"],correcta:1,explicacion:"El número va en negrita. El título en cursiva en la línea siguiente."},
        {id:"q68",texto:"¿Dónde se coloca número y título de una FIGURA en APA 7?",opciones:["Encima","Debajo","Dentro","Al inicio"],correcta:1,explicacion:"En figuras: número y título van DEBAJO del gráfico."},
        {id:"q69",texto:"¿Cuál es la diferencia entre tablas y figuras en APA 7?",opciones:["Tablas arriba; Figuras abajo","Ambas arriba","Ambas abajo","No hay diferencia"],correcta:0,explicacion:"Tablas: número encima. Figuras: número debajo."},
        {id:"q70",texto:"¿Cómo empieza una nota en tabla o figura APA 7?",opciones:["Fuente:","Nota:","Nota. en cursiva con punto","Con número entre corchetes"],correcta:2,explicacion:"Las notas empiezan con Nota. en cursiva seguida de punto."}
       ]},
      {id:"L3-5",titulo:"Casos Especiales",emoji:"🎯",xp:50,
       teoria:"<h3>Casos Especiales en APA 7</h3><div class=\"tex ok\"><span class=\"tlb\">Organización como autor</span><p>Primera vez: Organización Mundial de la Salud [OMS] (2020)<br>Siguientes: OMS (2020)</p></div><div class=\"tex ok\"><span class=\"tlb\">Comunicaciones personales</span><p>Solo en texto, NUNCA en referencias:<br>(J. García, comunicación personal, 5 marzo 2021)</p></div>",
       preguntas:[
        {id:"q71",texto:"¿Cómo se cita una organización como autor por PRIMERA vez?",opciones:["(OMS, 2020)","(Organización Mundial de la Salud [OMS], 2020)","(Organización, 2020)","(OMS: Organización, 2020)"],correcta:1,explicacion:"Primera mención: nombre completo + abreviatura. Después: solo abreviatura."},
        {id:"q72",texto:"¿Las comunicaciones personales van en la lista de referencias?",opciones:["Sí, siempre","No, solo en cita en el texto","Sí, con fecha de acceso","No, nunca se citan"],correcta:1,explicacion:"No van en referencias porque no son recuperables."},
        {id:"q73",texto:"¿Cuál es el ERROR en: García, Juan. (2020). Psicología. Planeta.?",opciones:["No hay error","Nombre completo — debe ser inicial: García, J.","Falta el DOI","Título entre comillas"],correcta:1,explicacion:"En APA 7 se usa solo la inicial del nombre."},
        {id:"q74",texto:"¿Cuál es el ERROR en: (García y López, 2019)?",opciones:["No hay error","Dentro del paréntesis debe ser & : (García & López, 2019)","Falta la página","El año debe ir antes"],correcta:1,explicacion:"Dentro de paréntesis se usa &, no y."},
        {id:"q75",texto:"¿Qué elemento adicional lleva la referencia de una tesis?",opciones:["El nombre del asesor","[Tipo de tesis, Universidad] antes del repositorio","Número de páginas","El resumen"],correcta:1,explicacion:"Las tesis incluyen [tipo y universidad] antes del repositorio."}
       ]}
     ]}
  ],
  guia:[
    {id:"g1",categoria:"Introducción",titulo:"¿Qué son las Normas APA?",icono:"📖",contenido:"<h2>Normas APA — 7ma Edición</h2><p>Las <strong>Normas APA</strong> son directrices de escritura académica de la <em>American Psychological Association</em>.</p><h3>Cambios APA 7 vs APA 6</h3><table class=\"gtbl\"><tr><th>Elemento</th><th>APA 6</th><th>APA 7</th></tr><tr><td>3+ autores en texto</td><td>Primera vez: todos</td><td>Siempre et al.</td></tr><tr><td>Lugar publicación</td><td>Obligatorio</td><td>Eliminado</td></tr><tr><td>Recuperado de</td><td>Obligatorio</td><td>Eliminado</td></tr></table>"},
    {id:"g2",categoria:"Formato",titulo:"Formato del Documento",icono:"📄",contenido:"<h2>Configuración del Documento APA 7</h2><table class=\"gtbl\"><tr><th>Elemento</th><th>Especificación</th></tr><tr><td>Márgenes</td><td>2.54 cm en todos los lados</td></tr><tr><td>Fuentes</td><td>Arial 11pt · Times New Roman 12pt</td></tr><tr><td>Interlineado</td><td>Doble en todo el documento</td></tr><tr><td>Alineación</td><td>Izquierda (flush left)</td></tr><tr><td>Sangría</td><td>1.27 cm inicio de párrafo</td></tr></table>"},
    {id:"g3",categoria:"Citas",titulo:"Citas en el Texto",icono:"✏️",contenido:"<h2>Citas en el Texto</h2><h3>Cita narrativa</h3><div class=\"gex\">García (2020) afirmó que la educación transforma.</div><h3>Cita parentética</h3><div class=\"gex\">(García, 2020)</div><h3>¿Cuándo citar?</h3><ul><li>Al copiar palabras textuales</li><li>Al parafrasear ideas</li><li>Al resumir información</li></ul>"},
    {id:"g4",categoria:"Citas",titulo:"Citas Directas",icono:"💬",contenido:"<h2>Citas Directas</h2><h3>Cortas (&lt;40 palabras)</h3><div class=\"gex\">García (2020) señaló que <em>la educación es la base del desarrollo</em> (p. 45).</div><h3>En Bloque (40+ palabras)</h3><ul><li>Nueva línea, sangría 1.27 cm</li><li>Sin comillas</li><li>Punto ANTES del paréntesis: ...texto. (García, 2020, p. 45)</li></ul>"},
    {id:"g5",categoria:"Citas",titulo:"Múltiples Autores",icono:"👥",contenido:"<h2>Múltiples Autores</h2><table class=\"gtbl\"><tr><th>N</th><th>Narrativa</th><th>Parentética</th></tr><tr><td>1</td><td>García (2020)</td><td>(García, 2020)</td></tr><tr><td>2</td><td>García y López (2020)</td><td>(García &amp; López, 2020)</td></tr><tr><td>3+</td><td>García et al. (2020)</td><td>(García et al., 2020)</td></tr></table><p><strong>&amp;</strong> dentro del paréntesis · <strong>y</strong> fuera del paréntesis</p>"},
    {id:"g6",categoria:"Referencias",titulo:"Lista de Referencias",icono:"📋",contenido:"<h2>Lista de Referencias</h2><ul><li>Nueva página: título Referencias centrado en negrita</li><li>Orden alfabético por apellido</li><li>Sangría francesa (segunda línea sangrada)</li><li>Interlineado doble</li><li>Sin lugar de publicación en libros</li><li>Sin Recuperado de</li></ul>"},
    {id:"g7",categoria:"Referencias",titulo:"Referencias de Libros",icono:"📚",contenido:"<h2>Libros — APA 7</h2><h3>Un autor</h3><div class=\"gex\">Apellido, I. (Año). <em>Título</em>. Editorial.</div><h3>Editor</h3><div class=\"gex\">Apellido, I. (Ed.). (Año). <em>Título</em>. Editorial.</div><h3>Capítulo en libro editado</h3><div class=\"gex\">Apellido, I. (Año). Título capítulo. En I. Editor (Ed.), <em>Título libro</em> (pp. XX-XX). Editorial.</div>"},
    {id:"g8",categoria:"Referencias",titulo:"Referencias de Artículos",icono:"📰",contenido:"<h2>Artículos de Revista — APA 7</h2><div class=\"gex\">Apellido, I. (Año). Título artículo. <em>Nombre Revista, Vol</em>(Núm), pp-pp. https://doi.org/xxx</div><p><em>Cursiva:</em> nombre de revista y volumen. El número entre paréntesis NO en cursiva.</p>"},
    {id:"g9",categoria:"Referencias",titulo:"Referencias Web",icono:"🌐",contenido:"<h2>Páginas Web — APA 7</h2><h3>Con autor</h3><div class=\"gex\">Apellido, I. (Año, día mes). <em>Título</em>. Sitio. URL</div><h3>Sin autor</h3><div class=\"gex\"><em>Título</em>. (Año). Sitio. URL</div><table class=\"gtbl\"><tr><th>APA 6</th><th>APA 7</th></tr><tr><td>Recuperado de https://...</td><td>https://...</td></tr></table>"},
    {id:"g10",categoria:"Referencias",titulo:"DOI y URLs",icono:"🔗",contenido:"<h2>DOI y URLs en APA 7</h2><ul><li>Formato: https://doi.org/10.XXXX/XXXX</li><li>Si hay DOI, no incluyas la URL</li><li>NO punto al final</li><li>NO Recuperado de</li></ul><table class=\"gtbl\"><tr><th>Antiguo</th><th>APA 7</th></tr><tr><td>doi:10.1234/ej</td><td>https://doi.org/10.1234/ej</td></tr></table>"},
    {id:"g11",categoria:"Formato",titulo:"Tablas y Figuras",icono:"📊",contenido:"<h2>Tablas y Figuras — APA 7</h2><h3>TABLAS — arriba</h3><div class=\"gex\"><strong>Tabla 1</strong><br><em>Título</em><br>[tabla]<br><em>Nota.</em> Info.</div><h3>FIGURAS — abajo</h3><div class=\"gex\">[imagen]<br><strong>Figura 1</strong><br><em>Título</em><br><em>Nota.</em> Fuente.</div>"},
    {id:"g12",categoria:"Especial",titulo:"Casos Especiales",icono:"⭐",contenido:"<h2>Casos Especiales APA 7</h2><h3>Organizaciones</h3><div class=\"gex\">Primera: Organización Mundial de la Salud [OMS] (2020)<br>Siguientes: OMS (2020)</div><h3>Comunicaciones personales</h3><div class=\"gex\">Solo en texto: (J. García, comunicación personal, 5 marzo 2021)</div><h3>Fuentes secundarias</h3><div class=\"gex\">García (2018, como se citó en López, 2021)</div>"},
    {id:"g13",categoria:"Especial",titulo:"Errores Frecuentes",icono:"⚠️",contenido:"<h2>Errores Frecuentes APA 7</h2><table class=\"gtbl\"><tr><th>Error</th><th>Correcto</th></tr><tr><td>García, Juan. (2020)</td><td>García, J. (2020)</td></tr><tr><td>García &amp; López (2020) dijeron</td><td>García y López (2020) dijeron</td></tr><tr><td>(García y López, 2020)</td><td>(García &amp; López, 2020)</td></tr><tr><td>Recuperado de https://</td><td>https://</td></tr><tr><td>México: UNAM.</td><td>UNAM.</td></tr><tr><td>doi:10.1234/xx</td><td>https://doi.org/10.1234/xx</td></tr><tr><td>pág. 45</td><td>p. 45</td></tr></table>"}
  ]
};